flags:
  app.froid:
    carryforward: false

  app.gooleplay:
    carryforward: false

ignore:
  - "**/androidTest/**/*.kt"
  - "**/androidTest/**/*.java"
  - "**/test/**/*.kt"
  - "**/test/**/*.java"
