flags:
  test.fdroid:
    carryforward: false

  test.googleplay:
    carryforward: false

  androidTest.fdroid:
    carryforward: false

  androidTest.googleplay:
    carryforward: false

  androidTest.espresso.fdroid:
    carryforward: false

  androidTest.uiautomator.fdroid:
    carryforward: false
